[package]
name = "wambo"
description = "Wambo - Decimal, Hex, Bin number + byte converter. Binary/CLI by a developer - for developers."
version = "0.1.0"
authors = ["Philipp Schuster <phip1611@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
