[package]
name = "wambo"
description = "Wambo - All-in-one binary that converts decimal/bin/hex + interprets input(bytes) as several (un)signed data types. A binary from a developer for developers."
version = "0.1.3"
authors = ["Philipp Schuster <phip1611@gmail.com>"]
edition = "2018"
keywords = ["converter", "binary", "hex", "hexadecimal", "bytes"]
categories = []
readme = "README.md"
license = "MIT"
homepage = "https://github.com/phip1611/wambo"
repository = "https://github.com/phip1611/wambo"
documentation = "https://docs.rs/wambo/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
